### ISSUE TITLE
Unable to install OJS with latest tag (ojs-3_1_1-4)

### ISSUE THREAD

**Issue by marcbria** [lucasdiedrich/ojs#14]
Hi Lucas,
today I got some time to test your work. Sorry for the delay.

To start, I tried a simple clean deploy with:
` $ docker run --name ojs -p 8087:80 -p 8448:443 -v /etc/localtime:/etc/localtime -d lucasdiedrich/ojs`

It rises a ojs-3_1_1-4 (that is good because 3.1.2-0 is still ongoing work) and initially looks like it's working. I can reach the first install screen, but after that I got a WSOD. Apache/php logs don't say much... plenty of messages like this:

`[Wed Mar 27 22:41:25.873409 2019] [core:warn] [pid 10] (99)Address not available: AH00056: connect to listener on [::]:80
`

 But second install page is redirected to "/index/install/install", that it's a suspicious url.

According to [this thread](https://forum.pkp.sfu.ca/t/solved-install-redirects-to-index-php-index-install/27905/4) it happens when the web server don't have support for PATHINFO.

Does it make sense?

I will try now with 3.1.2-0 (tagged as php7-test) to see what happens.

**Comment by lucasdiedrich** [comment]
Yeap, this could be probably changed over the Apache config file, we should have an AcceptPathInfo On.

Going to look over this.

**Comment by lucasdiedrich** [comment]
@marcbria can i send to the lastest tag?

**Comment by marcbria** [comment]
I will try to test it tonight. Crazy week. Sorry for the delay.
If you are in a hurry, please don't wait for my feedback.

**Comment by marcbria** [comment]
Ok.... I got some time now. :-)

I think I found where is the problem.

Let me go step by step, so you can stop me if we don't agree.

The goal is getting a clean OJS doing just this:
```
$ git clone https://github.com/lucasdiedrich/ojs.git
$ cd ojs
$ docker-compose up
```

But when I do this with master branch (unsure what label I'm testing in master :-)), config files are not found (apache.htaccess  ojs.config.inc.php  php.custom.ini) so docker-compose mount them as folders and the full stack crashes.

Till version 3.1.1-2 of your project, config files were files but in 3.1.1-4 you moved them:
* https://github.com/lucasdiedrich/ojs/tree/3.1.1-2/files
* files: https://github.com/lucasdiedrich/ojs/tree/3.1.1-4/files

Moving them to /etc/whaterver/conf.d folder is great but you only did for apache and php, but not for "ojs.config.inc.php". 

So, as a workaround, commenting ojs.config.inc.php volume line, did the job, and then the stack rises, but it's not a real solution because: 
a) config.ing.php is not persistent. 
b) docker-compose don't refer php and apache files correctly and config/* is useless.

Tomorrow I will try to fix this and (if you like) make you a PR.

BTW, in a different post dynamic config files are discussed:
https://github.com/lucasdiedrich/ojs/issues/17
I think this discussion need to be postponed till we decide the model.

Cheers,
m.

**Comment by lucasdiedrich** [comment]
@marcbria please ignore the tags version, i have rearranged the location of files, só instead of copying file by file we can copy everything using it path. About ojs.config.inc.php it never existed in the environment, i think you're confusing this file.

We really need to comment out some lines from docker-compose, focus in the ones who points out to files that doesn't exist yet.

**Comment by marcbria** [comment]
Good. Conversation followed at #22 to avoid problems mixing tags and branches.
Let's close this one.
