### ISSUE TITLE
Is "file" utility present in php:7.3-alpine image ?

### ISSUE THREAD

**Issue by Potomac** [lucasdiedrich/ojs#21]
Hello,

@lucasdiedrich @marcbria 

I need a confirmation : can you tell me if the "file" utility is present in the php:7.3-alpine image used by OJS docker image ?

My colleague notices a problem when he wants to upload an image file (as a submission) in OJS 3.1.2 docker image, he told me that he saw these messages in the console : 

```
sh: file: not found
[Tue Apr 09 13:13:38.938899 2019] [php7:warn] [pid 248] [client 10.0.0.7:58398] PHP Warning:  Declaration of IssueForm::fetch($request) should be compatible with Form::fetch($request, $template = NULL, $display = false) in /var/www/html/controllers/grid/issues/form/IssueForm.inc.php on line 23
```
I am not at work and I don't have a docker installation, so I can not reproduce the problem, can you confirm me that the file utility is not present in the alpine image used by ojs docker ?

"sh:file:not found" error message means that the system doesn't find "file" software in /usr/bin,

one solution is to install the package which provides file utility : 
https://pkgs.alpinelinux.org/package/edge/main/x86_64/file

**Comment by lucasdiedrich** [comment]
I can confirm that the "file" package is not included over the 7.3-alpine, going to fix this.

**Comment by lucasdiedrich** [comment]
Already commited @Potomac , please test the new version as soon as possible.

**Comment by Potomac** [comment]
thanks, I will test soon

**Comment by Potomac54** [comment]
Ok I did the test, the file utility is now present in the ojs container,

in fact I made a mistake :  the bug for the upload image is not during the submission process, but when we try to send an email from an OJS form, the "upload image" button doesn't work, I created a new issue which explains better the problem  : 
https://github.com/lucasdiedrich/ojs/issues/25

**Comment by lucasdiedrich** [comment]
OK, we can make everything from there so i'll close this issue. Thanks POTO*
