### ISSUE TITLE
Testing master branch

### ISSUE THREAD

**Issue by marcbria** [lucasdiedrich/ojs#27]
As in php7-test, master branch docker-compose.yml refers "latest" instead of "master".
I'm unsure about those changes because it's probably beter have more control and refer always specific tag versions. Please @lucasdiedrich review and set it what you think is better.

Changed variables to guarantee .env and docker-compose.yml were consistent and this time I also added OJS* variables to the .env file. Do you think is a good idea to keep all the vars in .env?

In this image I found a new issue, related with the private upload folder:
Dockerfile sets it to /var/www/html/files buit it's not a good idea to keep it exposed.

Changes included in PR #26 . 

After those changes, I made some basic testing and looks like "master" branch is working fine.

**Comment by lucasdiedrich** [comment]
Thanks for your PR @marcbria . Over the lastest commit i let the variables ONLY over the .env files to look more consistent. 

Thanks.
