### ISSUE TITLE
New release 3.1.2-1

### ISSUE THREAD

**Issue by marcbria** [lucasdiedrich/ojs#35]
Hi Lucas,

Sorry for the long silence. Overwhelmed with other stuff. :-(

Yesterday PKP released a new stable version (3.1.2-1) so I was wondering if you have time to update the docker.

Cheers,
m.

**Comment by marcbria** [comment]
Hi @lucasdiedrich 

No hurry, but would be nice to keep this sync with pkp releases.

Do you need help with this? As far as I remember, with the dockerfile you created, you only need to change the release number and the creation script will do all the magic, isn't it?

Here you have the last stable (3.1.2-1): https://github.com/pkp/ojs/tree/ojs-3_1_2-1

Thanks a lot for your time,
m.

**Comment by marcbria** [comment]
Thanks lucas.
Tested and is working fine (at least, installation).
I will test upgrade to see what happens.

BTW, I miss you for a long time and upgrade was important. 
What about a videoconf to organize future issues like this?
Do you mind to send mi a private message with your mail?

Cheers,
m.

**Comment by marcbria** [comment]
Ok... reporting "not working".
Installer looks fine, but when you run it you get the following error message:

> Errors occurred during installation Your server's PHP version is not supported by this software. 
> Double-check the installation requirements in docs/README. 

On header, it reports that:
> PHP >= 7.0.0; you are currently using PHP 5.6.40
> **WARNING: Your current version of PHP does not meet the minimum requirements for installation. It is recommended to upgrade to a more recent release of PHP.**

Logged into the container to check php and -v returns 5.6.40.

I pulled from dockerhub (lucasdietrich/ojs:master) that is where I see you made last changes.
Let me know if I missed the repo.

Cheers,
m.

PD: Please, say something about a videconf in september.

**Comment by lucasdiedrich** [comment]
@marcbria so in the latest version we must use php 7 as default. You really should use the php7-test branch/tag to test the latest version. So, i think, we should merge the php7-test to master and work only with php7 from now on.

Please, fell free to contact me at my personal email so we can make that videoconf, for faster communication you can also call me on hangouts. 

Thanks.

**Comment by marcbria** [comment]
Ok. The "test" part in the branch name was not very encouraging. :-)
The tags and baranches naming is something to talk about.
Let me test and I will be back with feedback, but merge sounds fine to me.

> Please, fell free to contact me at my personal email so we can make that videoconf, for faster communication you can also call me on hangouts.

I love to... but I don't have your personal mail :-)
Please, write me at marc.bria(a)gmail.com so we can talk privately.

Thanks for your work,
m.

**Comment by lucasdiedrich** [comment]
The "test" part was about to testing php7, once we integrate this project
with pkp it should use pkp tag names as expected. Going to reach you at
email. Thanks mark.

Em qui, 22 de ago de 2019 20:38, Marc Bria <notifications@github.com>
escreveu:
