### ISSUE TITLE
Missing dependency for texture plugin

### ISSUE THREAD

**Issue by marcbria** [lucasdiedrich/ojs#36]
Texture plugin requires simplexml.

Dockerfile need to install it as follows:
`$ apk add php7-xml php7-simplexml`

More info:
https://forum.pkp.sfu.ca/t/solved-texture-plugin-fails-with-call-to-undefined-function-simplexml-load-string/54446

**Comment by lucasdiedrich** [comment]
Thanks for that @marcbria , sorry for the late response.
