### ISSUE TITLE
Add support for Traeffik

### ISSUE THREAD

**Issue by lucasdiedrich** [lucasdiedrich/ojs#5]
Add support for treafik tags.

**Comment by jgonzalezr** [comment]
Hi @lucasdiedrich , 
I am wondering about the status of Traefik support? Could you please tell me if it works with the OJS container?
Best, 
Jorge

**Comment by lucasdiedrich** [comment]
Jorge, by my experience with traefik there is no such thing as traefik
support.

You can use labels on containers initialization and traefik will work
normally. Any doubts just ask.

Thanks.

Em sáb, 9 de fev de 2019 às 12:56, Jorge Gonzalez <notifications@github.com>
escreveu:
