### ISSUE TITLE
Lost dashboard

### ISSUE THREAD

**Issue by jobdiogenes** [lucasdiedrich/ojs#6]
I follow instruction, start docker
install ask basics fields, user,password, database host, ..
I filled,  send, and installation complete.

after Login, did not show dashboard.

This is a bug in last version of OJS or something in this docker?

**Comment by lucasdiedrich** [comment]
This is probably a bug from OJS version, since the docker is using *3.1.0-1* i will try to upgrade the docker to *3.1.1-2* as soon as possible.

**Comment by jobdiogenes** [comment]
I am making tests from scratch, not in  production environment or with some data.
I found that this a normal behavior.  (not a bug!?)
"Need at least two journals on the OJS instance 
 to global settings appear in the OJS menus."

I don't why they did this behavior. 

In any way, thanks to your fast answer.

**Comment by lucasdiedrich** [comment]
Anyway, i think you should open an request at [OJS Forum](https://forum.pkp.sfu.ca/) as this behavior seems odd. 

Thanks.
